- name: "Vars accessing from course details yaml file"
  hosts: web
  become: yes
  vars_files:
    - course-details.yml
  tasks:
    - name: "accessing course details"
      ansible.builtin.debug:
        msg: "course: {{ course }}, trainer: {{ trainer }}, duration: {{ duration }}"