- name: "Nginx installation and running"
  hosts: web
  become: yes
  tasks:
    - name: Install nginx
      ansible.builtin.pakage:
       name: nginx
       state: present

    - name: nginx
      ansible.builtin.service:
       name: nginx
       state: start
       enabled: yes