- name: checking priority wise vars executed
  hosts: local
  connection: local
  vars:
     NAME: "Ansible from Play level"
  vars_files:
  - course-details.yaml
  vars_prompt:
  - name: NAME
    prompt: "Enter your name:"
    private: false
  
  tasks:
  - name: print name
    vars:
       NAME: "Ansible from Task level"
    ansible.builtin.debug:
       msg: "Name: {{ NAME }}"

  