- name: "Conditions in Ansible"
  hosts: local
  connection: local
  vars:
    LIVE: true
    session: 7
  tasks:
  - name: "Printing completed sessions"
    ansible.builtin.debug:
      msg: " Yes, completed sessions are {{ session }}"
    when: session > 5

  - name: "Printing system is Alive or not"
    ansible.builtin.debug:
      msg: "Yes, System is Alive"
    when: LIVE