- name: Ansible Loop Packages
  hosts: localhost
  connection: local
  become: yes

  tasks:
  - name: Installing Packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
    - mysql
    - nginx
    - zip