- name: "Ansible Loop Packages"
  hosts: local
  connection: local

  tasks:
  - name: "Installing Packages"
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loops:
    - mysql
    - nginx
    - zip